### ISSUE TITLE
On a fresh install, trying to load an example PDB returns unsupported

### ISSUE THREAD

**Issue by neon-ninja** [UoA-eResearch/MolecularVive#1]

**Comment by neon-ninja** [comment]
Issue appears to be caused by special characters in the filename

**Comment by yangalan123** [comment]
Congratulations on bug fixing. I will give it a try and report anything wrong. Thank you for your hard work.

**Comment by neon-ninja** [comment]
resolved by https://github.com/UoA-eResearch/MolecularVive/commit/e87aa65f5303d6d3514b6e8948179278ab0090e1

**Comment by neon-ninja** [comment]
@yangalan123 - I've marked a new release as https://github.com/UoA-eResearch/MolecularVive/releases/tag/v1.05 - this should work even if there are . characters in the path
